# Generated by Django 4.2.29 on 2026-05-10 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_alter_category_slug'),
        ('products', '0009_product_sizes'),
        ('vendors', '0003_vendor_location_lat_vendor_location_lng'),
        ('orders', '0009_orderitem_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0017_riderprofile_rating_riderprofile_total_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Return Requested', 'Return Requested'), ('Vendor Review Pending', 'Vendor Review Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pickup Scheduled', 'Pickup Scheduled'), ('Picked Up', 'Picked Up'), ('Delivered to Vendor', 'Delivered to Vendor'), ('Product Inspection', 'Product Inspection'), ('Refund Processing', 'Refund Processing'), ('Refund Completed', 'Refund Completed'), ('Cancelled', 'Cancelled')], default='Return Requested', max_length=30)),
                ('refund_method', models.CharField(choices=[('Original Payment Method', 'Original Payment Method'), ('Wallet', 'Wallet'), ('Bank Transfer', 'Bank Transfer')], default='Wallet', max_length=30)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('inspection_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_returns', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_pickups', to='tracking.riderprofile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_returns', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='returns.returnrequest')),
            ],
            options={
                'verbose_name_plural': 'Return status histories',
            },
        ),
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_window_days', models.PositiveIntegerField(default=7)),
                ('is_returnable', models.BooleanField(default=True)),
                ('policy_text', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_policies', to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='returns/proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='returns.returnrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_size', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='products.product')),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange', to='returns.returnrequest')),
            ],
        ),
    ]
