# Generated by Django 4.2.29 on 2026-05-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnimage',
            name='is_inspection_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='inspection_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_account_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='vendor_decision',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='refund_method',
            field=models.CharField(choices=[('Original Payment Method', 'Original Payment Method'), ('Wallet', 'Wallet'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI')], default='Wallet', max_length=30),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('Return Requested', 'Return Requested'), ('Approved by Vendor', 'Approved by Vendor'), ('Pickup Assigned', 'Pickup Assigned'), ('Picked Up from Customer', 'Picked Up from Customer'), ('Delivered to Vendor', 'Delivered to Vendor'), ('Vendor Confirmed Received', 'Vendor Confirmed Received'), ('Inspection Started', 'Inspection Started'), ('Refund Approved', 'Refund Approved'), ('Refund Processed', 'Refund Processed'), ('Refund Rejected', 'Refund Rejected'), ('Cancelled', 'Cancelled')], default='Return Requested', max_length=30),
        ),
    ]
