# Generated by Django 4.2.29 on 2026-05-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_returnimage_is_inspection_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='inspection_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='inspection_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('Return Requested', 'Return Requested'), ('Approved by Vendor', 'Approved by Vendor'), ('Pickup Assigned', 'Pickup Assigned'), ('Picked Up from Customer', 'Picked Up from Customer'), ('Delivered to Vendor', 'Delivered to Vendor'), ('Vendor Confirmed Received', 'Vendor Confirmed Received'), ('Inspection Started', 'Inspection Started'), ('Return Accepted', 'Return Accepted'), ('Return Rejected by Vendor', 'Return Rejected by Vendor'), ('Admin Review', 'Admin Review'), ('Refund Approved', 'Refund Approved'), ('Refund Processed', 'Refund Processed'), ('Refund Rejected', 'Refund Rejected'), ('Cancelled', 'Cancelled')], default='Return Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='vendor_decision',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
