# Generated by Django 4.2.29 on 2026-05-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_returnrequest_inspection_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
