# Generated by Django 4.2.29 on 2026-04-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='label_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='parcel_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'Packed'), ('Ready for Dispatch', 'Ready for Dispatch'), ('Assigned', 'Assigned'), ('Dispatched', 'Dispatched'), ('Out for Delivery', 'Out for Delivery'), ('In Transit', 'In Transit'), ('Reached', 'Reached'), ('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Returned', 'Returned')], default='Pending', max_length=30),
        ),
    ]
