# Generated by Django 4.2.29 on 2026-04-21 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_shipment_label_printed_shipment_parcel_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='availability_status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=20),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
