# Generated by Django 4.2.29 on 2026-04-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_riderwallet_transaction_salaryconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Pending Assignment', 'Pending Assignment'), ('Assigned', 'Assigned'), ('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending', max_length=30),
        ),
    ]
