# Generated by Django 4.2.29 on 2026-04-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Dispatch Queue', 'Dispatch Queue'), ('Assigned', 'Assigned'), ('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending', max_length=30),
        ),
    ]
