# Generated by Django 4.2.29 on 2026-04-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_alter_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderwallet',
            name='pending_cod_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='riderwallet',
            name='shortage_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='RiderSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_deliveries', models.IntegerField(default=0)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incentives', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='tracking.riderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RiderFinancialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('log_type', models.CharField(choices=[('Incentive', 'Delivery Incentive'), ('Bonus', 'Performance Bonus'), ('Deduction', 'Deduction/Shortage'), ('Adjustment', 'Manual Adjustment')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_logs', to='tracking.riderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CODCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Submission'), ('Submitted', 'Submitted to Admin'), ('Disputed', 'Disputed/Shortage')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cod_collections', to='tracking.riderprofile')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cod_collection', to='tracking.shipment')),
            ],
        ),
    ]
