# Generated by Django 4.2.29 on 2026-04-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_riderwallet_pending_cod_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codcollection',
            name='submitted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
