# Generated by Django 4.2.29 on 2026-04-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_codcollection_submitted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderwallet',
            name='total_cod_submitted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
