# Generated by Django 4.2.29 on 2026-04-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_riderwallet_total_cod_collected'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveOrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.riderprofile')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_tracking', to='tracking.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
