# Generated by Django 4.2.29 on 2026-04-30 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_latitude_order_longitude'),
        ('tracking', '0011_liveordertracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderMonthlySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('completed_deliveries', models.IntegerField(default=0)),
                ('per_order_incentive', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('attendance_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fuel_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('late_penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_shortage_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_settlements', to='tracking.riderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RiderSalaryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Delivery Earnings', 'Delivery Earnings'), ('Distance Bonus', 'Distance Bonus'), ('Peak Hour Bonus', 'Peak Hour Bonus'), ('Referral Bonus', 'Referral Bonus'), ('Penalty', 'Penalty')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_transactions', to='tracking.riderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RiderWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cash Handover', 'Cash Handover')], max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='riders/cod_proofs/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted Awaiting Approval'), ('Verified', 'Verified by Admin'), ('Rejected', 'Rejected')], default='Submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='tracking.riderprofile')),
            ],
        ),
        migrations.RenameField(
            model_name='codcollection',
            old_name='collected_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='codcollection',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='codcollection',
            name='submitted_amount',
        ),
        migrations.AlterField(
            model_name='codcollection',
            name='status',
            field=models.CharField(choices=[('Pending', 'Rider Holding Cash'), ('Submitted', 'Submitted to Admin'), ('Verified', 'Verified by Admin'), ('Shortage', 'Shortage/Difference')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='RiderSettlement',
        ),
    ]
