# Generated by Django 4.2.29 on 2026-04-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_ridermonthlysettlement_ridersalarytransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codcollection',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codcollection',
            name='submitted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
