# Generated by Django 4.2.29 on 2026-04-30 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_codcollection_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderwallettransaction',
            name='cod_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='tracking.codcollection'),
        ),
    ]
