# Generated by Django 4.2.29 on 2026-05-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_riderwallettransaction_cod_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridermonthlysettlement',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
