# Generated by Django 4.2.29 on 2026-05-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_ridermonthlysettlement_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('incentive_type', models.CharField(choices=[('Milestone', 'Milestone Bonus'), ('PeakHour', 'Peak Hour Bonus'), ('Manual', 'Manual Admin Bonus')], default='Manual', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='tracking.riderprofile')),
            ],
        ),
    ]
