# Generated by Django 4.2.29 on 2026-05-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_riderincentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
