# Generated by Django 4.2.29 on 2026-05-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_riderprofile_rating_riderprofile_total_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='start_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Dispatch Queue', 'Dispatch Queue'), ('Assigned', 'Assigned'), ('Start Pickup', 'Start Pickup'), ('Picked Up', 'Picked Up'), ('Start Delivery', 'Start Delivery'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending', max_length=30),
        ),
    ]
