# Generated by Django 4.2.29 on 2026-05-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_shipment_assigned_at_shipment_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='id_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='riders/docs/id_proof/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='riders/docs/license/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='riders/docs/profile/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending Verification'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Suspended', 'Suspended')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
