# Generated by Django 4.2.29 on 2026-05-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_riderprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderprofile',
            old_name='emergency_contact',
            new_name='emergency_contact_phone',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='bank_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='riders/docs/bank/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='insurance_valid_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='rc_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='riders/vehicles/'),
        ),
    ]
