# Generated by Django 4.2.29 on 2026-05-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_rename_emergency_contact_riderprofile_emergency_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
