# Generated by Django 4.2.29 on 2026-05-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_riderprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
