# Generated by Django 4.2.29 on 2026-04-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('vendor', 'Vendor'), ('user', 'User'), ('rider', 'Rider')], default='user', max_length=20),
        ),
    ]
