# Generated by Django 4.2.29 on 2026-05-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
