# Generated by Django 4.2.29 on 2026-04-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
