# Generated by Django 4.2.29 on 2026-05-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_city_vendor_pickup_contact_vendor_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='alternative_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='delivery_radius',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='estimated_dispatch_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pickup_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_banner',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_banners/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_logos/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='working_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
