# Generated by Django 4.2.29 on 2026-04-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='QuanStore', max_length=100)),
                ('global_commission', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('auto_update_check', models.BooleanField(default=True)),
                ('last_update_check', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
