# Generated by Django 4.2.29 on 2026-05-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='facebook_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='instagram_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='linkedin_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='support_email',
            field=models.EmailField(blank=True, default='support@quanstore.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='support_phone',
            field=models.CharField(blank=True, default='+91 9876543210', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='twitter_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
