# Generated by Django 4.2.29 on 2026-05-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_platformsetting_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='payment_cod',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='payment_paypal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='payment_razorpay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='payment_wallet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='store_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='tax_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='tax_type',
            field=models.CharField(default='GST', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
    ]
