# Generated by Django 4.2.29 on 2026-05-14 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0018_shipment_assigned_at_shipment_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderPayrollRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveries_milestone', models.IntegerField(help_text='Number of deliveries for this incentive level')),
                ('incentive_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('petrol_rate_per_km', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('late_delivery_penalty', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('failed_delivery_penalty', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('cod_delay_penalty', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['deliveries_milestone'],
            },
        ),
        migrations.CreateModel(
            name='RiderWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_salary_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('last_payout_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_wallet', to='tracking.riderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RiderSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deliveries_count', models.IntegerField(default=0)),
                ('delivery_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_incentive', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('petrol_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('late_deliveries', models.IntegerField(default=0)),
                ('failed_deliveries', models.IntegerField(default=0)),
                ('penalties_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_settlements', to='tracking.riderprofile')),
            ],
            options={
                'ordering': ['-month', '-created_at'],
                'unique_together': {('rider', 'month')},
            },
        ),
        migrations.CreateModel(
            name='RiderPaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('settlement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_log', to='payroll.ridersettlement')),
            ],
        ),
    ]
