# Generated by Django 4.2.29 on 2026-05-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_deliveries', models.IntegerField(help_text='Minimum deliveries to qualify for this bonus')),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_deliveries'],
            },
        ),
        migrations.CreateModel(
            name='PayrollConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petrol_km_limit', models.IntegerField(default=5, help_text='KM limit for petrol allowance')),
                ('petrol_rate_per_km', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PenaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_name', models.CharField(help_text='e.g. Late Delivery, Failed Delivery', max_length=100)),
                ('deduction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='riderpayrollrule',
            options={},
        ),
        migrations.RemoveField(
            model_name='riderpayrollrule',
            name='cod_delay_penalty',
        ),
        migrations.RemoveField(
            model_name='riderpayrollrule',
            name='deliveries_milestone',
        ),
        migrations.RemoveField(
            model_name='riderpayrollrule',
            name='failed_delivery_penalty',
        ),
        migrations.RemoveField(
            model_name='riderpayrollrule',
            name='incentive_amount',
        ),
        migrations.RemoveField(
            model_name='riderpayrollrule',
            name='late_delivery_penalty',
        ),
        migrations.RemoveField(
            model_name='riderpayrollrule',
            name='petrol_rate_per_km',
        ),
        migrations.RemoveField(
            model_name='riderpayrollrule',
            name='updated_at',
        ),
    ]
