# Generated by Django 4.2.29 on 2026-05-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_deliverybonusrule_payrollconfiguration_penaltyrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTypePaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(help_text='e.g. Bike, Scooter, Bicycle', max_length=50, unique=True)),
                ('base_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('extra_per_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('night_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vehicle_type'],
            },
        ),
    ]
