# Generated by Django 4.2.29 on 2026-05-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_vehicletypepaysetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletypepaysetting',
            name='extra_per_km',
        ),
        migrations.RemoveField(
            model_name='vehicletypepaysetting',
            name='night_bonus',
        ),
    ]
