# Generated by Django 4.2.29 on 2026-04-27 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0003_vendor_location_lat_vendor_location_lng'),
        ('products', '0003_product_quantity_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Catchy title for the banner', max_length=255)),
                ('short_description', models.TextField(help_text='Brief marketing text')),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.IntegerField(default=0)),
                ('banner_image', models.ImageField(blank=True, help_text='Optional custom banner image. If empty, product image will be used.', null=True, upload_to='promotions/banners/')),
                ('background_color', models.CharField(default='#6D28D9', help_text='Hex color for banner background', max_length=7)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('priority', models.IntegerField(default=0, help_text='Higher priority banners show first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
