# Generated by Django 4.2.29 on 2026-04-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionbanner',
            name='background_color',
            field=models.CharField(default='#6D28D9', help_text='Hex color or CSS gradient for banner background', max_length=255),
        ),
    ]
