# Generated by Django 4.2.29 on 2026-04-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_alter_promotionbanner_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionbanner',
            name='badge_text',
            field=models.CharField(blank=True, help_text="e.g. 'Limited Offer' or 'Bestseller'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promotionbanner',
            name='border_radius',
            field=models.IntegerField(default=16, help_text='Border radius in pixels'),
        ),
        migrations.AddField(
            model_name='promotionbanner',
            name='button_bg_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='promotionbanner',
            name='button_text',
            field=models.CharField(default='Shop Now', max_length=50),
        ),
        migrations.AddField(
            model_name='promotionbanner',
            name='button_text_color',
            field=models.CharField(default='#0F172A', max_length=7),
        ),
        migrations.AddField(
            model_name='promotionbanner',
            name='description_color',
            field=models.CharField(default='#F3F4F6', max_length=7),
        ),
        migrations.AddField(
            model_name='promotionbanner',
            name='gradient_color_1',
            field=models.CharField(blank=True, help_text='Starting color for gradient', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='promotionbanner',
            name='gradient_color_2',
            field=models.CharField(blank=True, help_text='Ending color for gradient', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='promotionbanner',
            name='gradient_direction',
            field=models.CharField(choices=[('to right', 'Horizontal (To Right)'), ('to left', 'Horizontal (To Left)'), ('to bottom', 'Vertical (To Bottom)'), ('to top', 'Vertical (To Top)'), ('135deg', 'Diagonal (135deg)'), ('45deg', 'Diagonal (45deg)')], default='135deg', max_length=20),
        ),
        migrations.AddField(
            model_name='promotionbanner',
            name='image_position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center/Full Background')], default='right', max_length=10),
        ),
        migrations.AddField(
            model_name='promotionbanner',
            name='overlay_opacity',
            field=models.FloatField(default=0.2, help_text='Opacity of overlay if image exists (0.0 to 1.0)'),
        ),
        migrations.AddField(
            model_name='promotionbanner',
            name='title_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='promotionbanner',
            name='background_color',
            field=models.CharField(default='#6D28D9', help_text='Base background color', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotionbanner',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Optional custom banner image.', null=True, upload_to='promotions/banners/'),
        ),
    ]
