# Generated by Django 4.2.29 on 2026-04-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_vendorpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('COD Pending', 'COD Pending'), ('COD Collected', 'COD Collected'), ('Refunded', 'Refunded'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Chargeback', 'Chargeback')], default='Pending', max_length=20),
        ),
    ]
