# Generated by Django 4.2.29 on 2026-05-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_gateway_reference_payment_refund_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayout',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('manual', 'Manual')], default='bank_transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Hold', 'Hold'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
