# Generated by Django 4.2.29 on 2026-05-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_refund_date_payment_refund_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpayout',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Refund Hold', 'Refund Hold'), ('Cancelled', 'Cancelled'), ('Released', 'Released'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
