# Generated by Django 4.2.29 on 2026-05-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_vendorpayout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayout',
            name='refundStatus',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='returnEligibleUntil',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='returnRequestedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='settlementReleasedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='settlementStatus',
            field=models.CharField(choices=[('RETURN_HOLD', 'RETURN_HOLD'), ('READY_FOR_PAYOUT', 'READY_FOR_PAYOUT'), ('SETTLED', 'SETTLED'), ('REFUND_HOLD', 'REFUND_HOLD'), ('REFUNDED', 'REFUNDED')], default='RETURN_HOLD', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Refund Hold', 'Refund Hold'), ('Cancelled', 'Cancelled'), ('Released', 'Released'), ('Failed', 'Failed'), ('Hold', 'Hold'), ('RETURN_HOLD', 'RETURN_HOLD'), ('READY_FOR_PAYOUT', 'READY_FOR_PAYOUT'), ('SETTLED', 'SETTLED'), ('REFUND_HOLD', 'REFUND_HOLD'), ('REFUNDED', 'REFUNDED')], default='Pending', max_length=20),
        ),
    ]
