# Generated by Django 4.2.29 on 2026-04-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('ml', 'Milliliter (ml)'), ('l', 'Liter (l)'), ('pcs', 'Pieces (pcs)')], default='pcs', max_length=10),
        ),
    ]
