# Generated by Django 4.2.29 on 2026-04-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_quantity_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
