# Generated by Django 4.2.29 on 2026-05-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_cod',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_paypal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_razorpay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_wallet',
            field=models.BooleanField(default=True),
        ),
    ]
